apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-ruby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: kimitsu/rails-app:v0.0.2
          command:
            - /bin/bash
          args:
            - -c
            - rails assets:precompile && rails server -b 0.0.0.0
          env:
            - name: DATABASE_URL
              value: postgres://postgres@sample-service-psql/postgres